### ISSUE TITLE
Can't install plugin on TrueNAS 12.2-RELEASE-p4 

### ISSUE THREAD

**Issue by chicco27** [AfroUSApl/iocage-plugin-piwigo#3]
I tried many times to install the plugin on my TrueNAS 12.2-RELEASE-p4 but the fails are still the same:

`Error: piwigo had a failure Exception: RuntimeError Message: pkg error: - php73 :,php73-exif :,php73-filter :,php73-gd :,php73-hash :,php73-mbstring :,php73-mysqli :,php73-json :,php73-session :,php73-zip :,php73-zlib : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed`

I use NAT option and all the rest conf is default.
I also tried to change the DNS resolver without any success. Other plugins work correctly.

Seems a problem with version packages of php73. Are they still available on this release?

**Comment by Attackly** [comment]
I have the Same Problem. 
Running TrueNAS-12.0-U8

**Comment by overflow-ITA** [comment]
I have the Same Problem.

Version:  
TrueNAS-12.0-U8

**Comment by Scout91** [comment]
I have the same problem with the instal.

i haven the same version of truenas

**Comment by hardwareadictos** [comment]
Same issue, switched to quarterly cycle but it also doesnt work

**Comment by CesMak** [comment]
same issue for me. Would be glad if sb has an idea how to solve this issue. Do I have to install manually? Is there any instrutions or should I switch completely to google prism?

**Comment by AfroUSApl** [comment]
Hi all,
Working on this issue now, sorry for late reply. Looks like there is an issue with not active PHP7.3, so need to get this update to most active version of PHP

**Comment by julianq** [comment]
Just wanted to check if this was ever fixed? Still getting the error.

**Comment by AfroUSApl** [comment]
Had a moment to fix some issues with Piwigo 13 update, now I have working iocage with 12.2 release and PHP74

**Comment by AfroUSApl** [comment]
Fixed withe the latest update to Piwigo 13, 12.2 release and PHP 7.4
