### ISSUE TITLE
Installation questions

### ISSUE THREAD

**Issue by zhangry868** [AfroUSApl/iocage-plugin-piwigo#8]
I can use the community plugin to successfully install. However, I can see the installation page but it will show 500 error after click the start installation.

When I am using this Git repo, it shows 12.2-Release not found.

Any suggestions on it? I am using TrueNAS-13.0-U3.1.

**Comment by AfroUSApl** [comment]
Hi, try to use Master, its updated to the recent version ;)

**Comment by adimajo** [comment]
Same; even after changing php73/74 => php80

root@Piwigo:/var/log # cat nginx-error.log
2023/02/07 19:28:25 [error] 8426#101920: *6 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class "DOMDocument" not found in /usr/local/www/Piwigo/include/emogrifier.class.php:406
Stack trace:
#0 /usr/local/www/Piwigo/include/emogrifier.class.php(233): Emogrifier->createXmlDocument()
#1 /usr/local/www/Piwigo/include/functions_mail.inc.php(951): Emogrifier->emogrify()
#2 /usr/local/www/Piwigo/include/functions_mail.inc.php(849): move_css_to_body()
#3 /usr/local/www/Piwigo/install.php(520): pwg_mail()
#4 {main}
  thrown in /usr/local/www/Piwigo/include/emogrifier.class.php on line 406" while reading response header from upstream, client: 192.168.1.64, server: piwigo.example.com, request: "POST /install.php?language=fr_FR HTTP/1.1", upstream: "fastcgi://unix:/var/run/piwigo.example.com-php-fpm.sock:", host: "192.168.1.93", referrer: "http://192.168.1.93/install.php"

**Comment by adimajo** [comment]
The following worked:

root@truenas[~/iocage-plugin-piwigo]# cat piwigo.json
{
    "name": "Piwigo",
    "plugin_schema": "2",
    "release": "13.1-RELEASE",
    "artifact": "https://github.com/AfroUSApl/iocage-plugin-piwigo.git",
    "official": false,
    "properties": {
        "vnet": 1,
        "dhcp": 1
    },
    "pkgs": [
        "ImageMagick7-nox11",
        "git",
        "nginx",
        "mariadb105-server",
        "php80",
        "php80-xml",
        "php80-dom",
        "php80-exif",
        "php80-filter",
        "php80-gd",
        "php80-mbstring",
        "php80-mysqli",
        "php80-session",
        "php80-zip",
        "php80-zlib",
        "finfo",
        "php80-fileinfo"
    ],
    "packagesite": "http://pkg.FreeBSD.org/${ABI}/quarterly",
    "fingerprints": {
        "iocage-plugins": [
            {
                "function": "sha256",
                "fingerprint": "b0170035af3acc5f3f3ae1859dc717101b4e6c1d0a794ad554928ca0cbb2f438"
            }
        ]
    },
    "revision": "0"
}
